services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
      - rabbitmq
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management
    networks:
      - evolution-net
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=33H2CdkzF5WrnJ4ud6nkUdRTKXvbCHeFjvVL71p
      - RABBITMQ_DEFAULT_VHOST=default
      - RABBITMQ_DEFAULT_USER=USER
      - RABBITMQ_DEFAULT_PASS=PASSWORD
    volumes:
      - evolution_rabbitmq:/rabbitmq_data/
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5434

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  evolution_rabbitmq:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
